#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

#Tamanho borda
bspc config border_width        1
#Tamanho entre janelas
bspc config window_gap          10
bspc config top_padding 	    35
bspc config bottom_pading	    0
bspc config left_padding 	    -4
bspc config right_padding	    -4

#Abre o Alacritty no 2 e centralizado uma vez so, as outras funciona normal [essa aqui foi brains]
#Quando o rice tiver completo, talvez ele abra no desktop 1 + algumas coisas
bspc rule -a Alacritty desktop=^1 state=floating rectangle=950x1017+965+53

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config automatic_scheme longest_side
bspc config normal border_color "#323e42"
bspc config focused_border_color "#efdcf9"
$HOME/.config/bspwm/launch.sh
